services:
  - type: web
    name: srijandev-platform-hub
    env: node
    region: singapore
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
