import { ServiceItem, PortfolioItem, BlogPost, PricingPlan, CareerOpening, CaseStudy } from '@/types/corporate';
import { Employee, AttendanceRecord, Task, CRMLead, DocumentItem, ActivityLog, DashboardMetrics } from '@/types/platform';

export const CORPORATE_SERVICES: ServiceItem[] = [
  {
    id: 'web-dev',
    slug: 'web-development',
    title: 'Enterprise Web Application Development',
    shortDesc: 'Custom high-performance web applications built with Next.js, React, and cloud-native serverless architecture.',
    fullDesc: 'SrijanDev builds scalable, secure, and resilient web applications for enterprises. From modern single-page apps to micro-frontend architectures, our solutions deliver lightning-fast response times, top SEO scores, and fluid user experiences.',
    icon: 'Code2',
    features: ['Next.js 15 & React 19', 'Server-Side Rendering (SSR)', 'Micro-Frontend Architecture', 'Headless CMS Integration'],
    benefits: ['Sub-second page load performance', 'Seamless multi-device responsiveness', 'Enterprise-grade security standards'],
    technologies: ['React', 'Next.js', 'TypeScript', 'TailwindCSS', 'Node.js', 'GraphQL'],
    startingPrice: '$4,999',
  },
  {
    id: 'ai-automation',
    slug: 'ai-and-automation',
    title: 'AI Engineering & Hyper-Automation',
    shortDesc: 'Harness LLMs, intelligent agents, and custom machine learning pipelines to automate complex workflows.',
    fullDesc: 'Transform operational productivity with custom AI agents, automated NLP document processing, predictive intelligence models, and seamless API integrations with enterprise databases.',
    icon: 'Cpu',
    features: ['Generative AI & RAG Systems', 'Custom LLM Fine-Tuning', 'Document Intelligence', 'Predictive Analytics Pipelines'],
    benefits: ['Reduce manual operational cost by up to 60%', '24/7 automated intelligent processing', 'Real-time insight generation'],
    technologies: ['Python', 'TensorFlow', 'PyTorch', 'LangChain', 'OpenAI', 'Vertex AI'],
    startingPrice: '$7,499',
  },
  {
    id: 'cloud-devops',
    slug: 'cloud-transformation',
    title: 'Cloud Architecture & DevOps Infrastructure',
    shortDesc: 'Cloud migration, Kubernetes orchestration, zero-downtime CI/CD pipelines, and infrastructure as code.',
    fullDesc: 'We architect resilient cloud solutions on AWS, GCP, and Azure. Modernize legacy monolithic systems into cloud-native microservices with robust monitoring, automated failover, and strict SAIF security compliance.',
    icon: 'Cloud',
    features: ['Multi-Cloud Migration', 'Kubernetes & Docker Orchestration', 'Terraform & IaC', '24/7 SRE Monitoring & Alerting'],
    benefits: ['99.99% infrastructure uptime', 'Automated zero-downtime deployments', 'Optimized cloud resource expenditure'],
    technologies: ['AWS', 'Google Cloud', 'Docker', 'Kubernetes', 'Terraform', 'Datadog'],
    startingPrice: '$5,999',
  },
  {
    id: 'erp-crm',
    slug: 'erp-crm-solutions',
    title: 'Enterprise ERP & Business Automation',
    shortDesc: 'Custom ERP and CRM platforms designed to unify workforce, supply chain, finances, and client pipelines.',
    fullDesc: 'Bridge operational silos with SrijanDev Enterprise Suite. Seamlessly integrate HR, attendance tracking, project management, payroll, sales pipeline analytics, and executive reporting in a single unified dashboard.',
    icon: 'Briefcase',
    features: ['Custom CRM Pipelines', 'Employee & Payroll Management', 'Financial Analytics & Audit Logs', 'Role-Based Access Control'],
    benefits: ['Single source of truth for business metrics', 'Streamlined cross-department workflows', 'Instant executive reporting'],
    technologies: ['PostgreSQL', 'Prisma', 'Next.js', 'Redis', 'TailwindCSS'],
    startingPrice: '$8,999',
  },
  {
    id: 'mobile-apps',
    slug: 'mobile-development',
    title: 'Cross-Platform Mobile App Development',
    shortDesc: 'High-performance mobile solutions for iOS and Android powered by React Native and Flutter.',
    fullDesc: 'Deliver native-like mobile apps with intuitive UI design, offline sync capabilities, push notification engines, and secure biometric authentication.',
    icon: 'Smartphone',
    features: ['iOS & Android Unified Codebase', 'Biometric Security', 'Offline First Sync Engine', 'Push Notification Automation'],
    benefits: ['Faster time-to-market across App Store & Play Store', 'Smooth 60FPS fluid UI animations'],
    technologies: ['React Native', 'Flutter', 'TypeScript', 'Firebase'],
    startingPrice: '$6,499',
  },
  {
    id: 'workforce-ops',
    slug: 'workforce-field-operations',
    title: 'Smart Workforce & Field Operations Suite',
    shortDesc: 'Complete workforce management platform for shift scheduling, geolocation check-ins, attendance, and expense tracking.',
    fullDesc: 'Inspired by modern operations platforms like Unolo, SrijanDev Workforce Suite empowers managers to track field staff check-ins, automate shift planning, process expense claims, and view real-time location metrics in a single dashboard.',
    icon: 'Briefcase',
    features: ['Geolocation Shift Check-In', 'Automated Shift Scheduling', 'Expense & Travel Reimbursement Claims', 'Timesheets & Attendance Audit'],
    benefits: ['Reduce workforce tracking errors by 90%', 'Automated shift alerts & manager approvals', 'Real-time location map feed'],
    technologies: ['Next.js 15', 'TypeScript', 'Prisma', 'PostgreSQL', 'TailwindCSS'],
    startingPrice: '$5,499',
  },
  {
    id: 'digital-consulting',
    slug: 'digital-transformation-consulting',
    title: 'Enterprise Architecture & IT Consulting',
    shortDesc: 'Strategic technology roadmap, legacy system modernization, security compliance audits, and performance tuning.',
    fullDesc: 'Inspired by top software consultancies like TechPurple, our senior software architects evaluate your technology stack, identify security bottlenecks, and guide legacy modernization into cloud-native microservices.',
    icon: 'Code2',
    features: ['Architectural Code Audits', 'Zero-Downtime Migration Strategy', 'SAIF & Security Compliance', 'Performance & Load Optimization'],
    benefits: ['Sub-second response time guarantee', 'Seamless legacy-to-cloud transition'],
    technologies: ['Next.js', 'React 19', 'Kubernetes', 'AWS', 'Python', 'Terraform'],
    startingPrice: '$7,999',
  },
];

export const PORTFOLIO_PROJECTS: PortfolioItem[] = [
  {
    id: 'proj-1',
    slug: 'fintech-global-platform',
    title: 'NexusPay Global Banking & Transfer Portal',
    category: 'web',
    client: 'Nexus Financial Group',
    image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=800&q=80',
    description: 'Real-time multi-currency transaction engine handling over $40M daily transfers with automated fraud detection.',
    results: ['99.999% system availability', '0.12s average API response time', 'Processed 3.5M transactions in Q1'],
    techStack: ['Next.js', 'TypeScript', 'Node.js', 'PostgreSQL', 'TailwindCSS'],
    testimonial: {
      quote: 'SrijanDev engineered a bulletproof platform that scaled seamlessly during peak market volatility.',
      author: 'Marcus Vance',
      role: 'CTO, Nexus Financial',
    },
  },
  {
    id: 'proj-2',
    slug: 'ai-health-diagnostic',
    title: 'MedAI Clinical Imaging & Document Processor',
    category: 'ai',
    client: 'Apex Health Systems',
    image: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=800&q=80',
    description: 'AI-assisted medical image analysis platform providing automated preliminary diagnostic insights for radiologists.',
    results: ['Reduced report turnaround time by 45%', '98.4% diagnostic accuracy rating', 'HIPAA compliant cloud deployment'],
    techStack: ['Python', 'PyTorch', 'FastAPI', 'React', 'Docker'],
    testimonial: {
      quote: 'The AI pipeline designed by SrijanDev has empowered our clinical staff to prioritize urgent patient cases faster.',
      author: 'Dr. Elena Rostova',
      role: 'Head of Clinical Innovation',
    },
  },
  {
    id: 'proj-3',
    slug: 'smart-workforce-saas',
    title: 'WorkOps Enterprise Workforce Platform',
    category: 'erp',
    client: 'Global Logistics Corp',
    image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=800&q=80',
    description: 'Comprehensive workforce management SaaS featuring automated shift scheduling, geolocation check-in, and KPI tracking.',
    results: ['Managed 12,000+ active field staff', 'Saved 350+ manager hours monthly', 'Zero payroll processing errors'],
    techStack: ['Next.js 15', 'Prisma', 'TailwindCSS', 'PostgreSQL', 'Framer Motion'],
  },
  {
    id: 'proj-4',
    slug: 'cloud-telecom-mesh',
    title: 'CloudMesh Multi-Region Infrastructure',
    category: 'cloud',
    client: 'Veloce Telecom',
    image: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=800&q=80',
    description: 'Cloud modernization and zero-downtime Kubernetes migration across 4 global AWS regions.',
    results: ['Reduced AWS infrastructure costs by 32%', 'Automated multi-region failover in < 5 seconds'],
    techStack: ['Kubernetes', 'Terraform', 'AWS Lambda', 'Prometheus', 'Go'],
  },
];

export const BLOG_POSTS: BlogPost[] = [
  {
    id: 'blog-1',
    slug: 'building-nextjs-15-enterprise-apps',
    title: 'Building Enterprise-Grade Web Applications with Next.js 15 and Server Components',
    excerpt: 'Explore advanced patterns for SSR, micro-frontends, caching strategies, and state hydration in large scale apps.',
    content: 'Next.js 15 introduces revolutionary performance improvements. In this technical deep dive, we explore how SrijanDev architects resilient web portals leveraging React Server Components, streaming SSR, and edge caching...',
    category: 'Engineering',
    author: {
      name: 'Rajesh Bhatti',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80',
      role: 'Principal Architect',
    },
    publishedAt: '2026-07-28',
    readTime: '6 min read',
    image: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=800&q=80',
    tags: ['Next.js', 'React', 'TypeScript', 'Web Architecture'],
  },
  {
    id: 'blog-2',
    slug: 'ai-agents-workforce-automation',
    title: 'How Autonomous AI Agents Are Transforming Business Operations in 2026',
    excerpt: 'From CRM lead scoring to automated code reviews, see how AI workflows are accelerating enterprise throughput.',
    content: 'Autonomous AI agents are no longer a theoretical novelty. Leading enterprises are embedding LLM workflows directly into operational dashboards...',
    category: 'Artificial Intelligence',
    author: {
      name: 'Aisha Sharma',
      avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=150&q=80',
      role: 'AI Research Lead',
    },
    publishedAt: '2026-07-15',
    readTime: '8 min read',
    image: 'https://images.unsplash.com/photo-1677442136019-21780efad99a?auto=format&fit=crop&w=800&q=80',
    tags: ['AI Agents', 'Automation', 'Machine Learning', 'SaaS'],
  },
];

export const PRICING_PLANS: PricingPlan[] = [
  {
    id: 'starter',
    name: 'Growth Tech',
    tagline: 'Ideal for scaling startups and modernizing SMB digital systems.',
    monthlyPrice: 1999,
    annualPrice: 1599,
    features: [
      'Custom Web App (Up to 10 Pages)',
      'Responsive Glassmorphism Design',
      'SEO & Performance Optimization (>95 Score)',
      'Standard REST API Integration',
      'Community Support & SLA',
    ],
    ctaText: 'Get Started',
  },
  {
    id: 'pro',
    name: 'Enterprise Business',
    tagline: 'Full-stack development, AI automation, and workforce platform integration.',
    monthlyPrice: 4999,
    annualPrice: 3999,
    popular: true,
    features: [
      'Full Multi-Portal Platform Setup',
      'Portal 1 (Corporate) & Portal 2 (SaaS Platform)',
      'Custom AI & Workflow Automation',
      'Dedicated Cloud DevOps Setup (AWS/GCP)',
      'Employee & Attendance CRM Modules',
      '24/7 Priority SRE Support & Dedicated Architect',
    ],
    ctaText: 'Launch Enterprise',
  },
  {
    id: 'custom',
    name: 'Custom Transformation',
    tagline: 'Tailored enterprise architecture for global organizations.',
    monthlyPrice: 9999,
    annualPrice: 8499,
    features: [
      'Bespoke Micro-Frontend & ERP Engineering',
      'Dedicated On-Prem or Cloud Deployment',
      'Custom Security Audits & Compliance',
      'Unlimited User Roles & Multi-tenant DB',
      'Guaranteed 99.99% SLA Uptime Contract',
    ],
    ctaText: 'Contact Sales',
  },
];

export const CAREER_OPENINGS: CareerOpening[] = [
  {
    id: 'car-1',
    title: 'Senior Full Stack Engineer (Next.js & TypeScript)',
    department: 'Engineering',
    location: 'Hybrid / Remote',
    type: 'Full-time',
    experience: '5+ Years',
    description: 'We are seeking an experienced Full Stack Architect to build resilient multi-portal applications using Next.js 15, React 19, TailwindCSS, and Prisma.',
    requirements: [
      'Deep proficiency with Next.js App Router, React Server Components, and TypeScript',
      'Experience with PostgreSQL, Prisma ORM, and Supabase / Clerk authentication',
      'Strong eye for modern glassmorphic UI design and Framer Motion micro-interactions',
    ],
  },
  {
    id: 'car-2',
    title: 'AI/ML Systems Engineer',
    department: 'Artificial Intelligence',
    location: 'Remote',
    type: 'Full-time',
    experience: '4+ Years',
    description: 'Lead the design and production deployment of RAG pipelines, fine-tuned LLM agents, and intelligent document extraction services.',
    requirements: [
      'Proven experience building LangChain or LlamaIndex workflows in Python',
      'Familiarity with OpenAI API, Vertex AI, and vector databases (Pinecone / Pgvector)',
      'Strong grasp of API integration and containerized microservices',
    ],
  },
];

export const CASE_STUDIES: CaseStudy[] = [
  {
    id: 'cs-1',
    slug: 'nexuspay-case-study',
    title: 'Scaling NexusPay to 3.5 Million Global Transactions',
    client: 'Nexus Financial',
    industry: 'FinTech',
    summary: 'How SrijanDev rebuilt NexusPay into a zero-latency, cloud-native payment portal.',
    challenge: 'Legacy database bottlenecks caused transaction timeouts during peak market trading hours.',
    solution: 'Re-architected backend with Next.js micro-services, Prisma connection pooling, and multi-region Redis caching.',
    metrics: [
      { label: 'Uptime', value: '99.999%' },
      { label: 'Latency', value: '120ms' },
      { label: 'Daily Volume', value: '$40M+' },
    ],
    image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=800&q=80',
  },
];

// Business SaaS Platform Mock Data
export const PLATFORM_METRICS: DashboardMetrics = {
  totalEmployees: 148,
  presentToday: 136,
  activeProjects: 24,
  monthlyRevenue: 184500,
  openTasks: 42,
  pendingLeaves: 6,
  conversionRate: 68.4,
};

export const PLATFORM_EMPLOYEES: Employee[] = [
  {
    id: 'emp-1',
    name: 'Rajesh Bhatti',
    email: 'rajesh@srijandev.com',
    role: 'Principal Platform Architect',
    userRole: 'ADMIN',
    department: 'Engineering',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80',
    status: 'active',
    joinedDate: '2022-01-15',
    phone: '+91 98765 43210',
    location: 'Bengaluru, India',
    taskCount: 8,
  },
  {
    id: 'emp-2',
    name: 'Aisha Sharma',
    email: 'aisha@srijandev.com',
    role: 'Lead AI Engineer',
    userRole: 'MANAGER',
    department: 'AI & Data',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=150&q=80',
    status: 'active',
    joinedDate: '2022-06-01',
    phone: '+91 98765 43211',
    location: 'Delhi, India',
    taskCount: 6,
  },
  {
    id: 'emp-3',
    name: 'David Chen',
    email: 'david@srijandev.com',
    role: 'Senior Product Designer',
    userRole: 'EMPLOYEE',
    department: 'UI/UX Design',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80',
    status: 'remote',
    joinedDate: '2023-02-10',
    phone: '+1 415 555 0199',
    location: 'San Francisco, USA',
    taskCount: 5,
  },
  {
    id: 'emp-4',
    name: 'Priya Nair',
    email: 'priya@srijandev.com',
    role: 'DevOps & SRE Manager',
    userRole: 'MANAGER',
    department: 'Operations',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=150&q=80',
    status: 'active',
    joinedDate: '2023-04-20',
    phone: '+91 98765 43212',
    location: 'Bengaluru, India',
    taskCount: 7,
  },
  {
    id: 'emp-5',
    name: 'Michael Miller',
    email: 'michael@srijandev.com',
    role: 'Client Success Director',
    userRole: 'MANAGER',
    department: 'Business Operations',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&q=80',
    status: 'on_leave',
    joinedDate: '2022-11-05',
    phone: '+44 20 7946 0912',
    location: 'London, UK',
    taskCount: 3,
  },
];

export const PLATFORM_ATTENDANCE: AttendanceRecord[] = [
  {
    id: 'att-1',
    employeeId: 'emp-1',
    employeeName: 'Rajesh Bhatti',
    date: '2026-08-03',
    checkIn: '09:02 AM',
    status: 'present',
    hoursWorked: 7.5,
    location: 'HQ Bengaluru',
  },
  {
    id: 'att-2',
    employeeId: 'emp-2',
    employeeName: 'Aisha Sharma',
    date: '2026-08-03',
    checkIn: '09:15 AM',
    status: 'present',
    hoursWorked: 7.2,
    location: 'Remote Delhi',
  },
  {
    id: 'att-3',
    employeeId: 'emp-3',
    employeeName: 'David Chen',
    date: '2026-08-03',
    checkIn: '09:45 AM',
    status: 'late',
    hoursWorked: 6.8,
    location: 'Remote USA',
  },
  {
    id: 'att-4',
    employeeId: 'emp-5',
    employeeName: 'Michael Miller',
    date: '2026-08-03',
    status: 'absent',
    hoursWorked: 0,
    location: 'On Leave',
  },
];

export const PLATFORM_TASKS: Task[] = [
  {
    id: 'task-101',
    title: 'Deploy Next.js 15 Multi-Portal Architecture',
    description: 'Finalize portal switching state, local storage persistence, and glassmorphic header navbar.',
    status: 'in_progress',
    priority: 'urgent',
    assignee: {
      id: 'emp-1',
      name: 'Rajesh Bhatti',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80',
    },
    dueDate: '2026-08-05',
    category: 'Architecture',
    commentsCount: 4,
  },
  {
    id: 'task-102',
    title: 'Fine-tune AI Agent RAG Document Extractor',
    description: 'Improve precision scores for clinical image processing pipelines.',
    status: 'in_progress',
    priority: 'high',
    assignee: {
      id: 'emp-2',
      name: 'Aisha Sharma',
      avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=150&q=80',
    },
    dueDate: '2026-08-08',
    category: 'AI Pipeline',
    commentsCount: 6,
  },
  {
    id: 'task-103',
    title: 'Design Glassmorphism Dashboard Dark Theme',
    description: 'Craft high-contrast charts, interactive Kanban cards, and floating action menus.',
    status: 'completed',
    priority: 'high',
    assignee: {
      id: 'emp-3',
      name: 'David Chen',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80',
    },
    dueDate: '2026-08-02',
    category: 'UI/UX Design',
    commentsCount: 2,
  },
  {
    id: 'task-104',
    title: 'AWS Multi-Region Failover Load Testing',
    description: 'Execute synthetic chaos engineering tests to simulate region outages.',
    status: 'todo',
    priority: 'medium',
    assignee: {
      id: 'emp-4',
      name: 'Priya Nair',
      avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=150&q=80',
    },
    dueDate: '2026-08-10',
    category: 'DevOps',
    commentsCount: 1,
  },
];

export const PLATFORM_LEADS: CRMLead[] = [
  {
    id: 'lead-1',
    companyName: 'Apex Health Systems',
    contactName: 'Dr. Elena Rostova',
    email: 'elena@apexhealth.com',
    phone: '+1 415 888 9911',
    value: 85000,
    stage: 'won',
    assignedTo: 'Aisha Sharma',
    createdAt: '2026-07-10',
  },
  {
    id: 'lead-2',
    companyName: 'Veloce Telecom Corp',
    contactName: 'Arthur Pendelton',
    email: 'arthur@veloce.io',
    phone: '+44 20 7111 2233',
    value: 120000,
    stage: 'negotiation',
    assignedTo: 'Rajesh Bhatti',
    createdAt: '2026-07-22',
  },
  {
    id: 'lead-3',
    companyName: 'Fintech Global Ltd',
    contactName: 'Sarah Jenkins',
    email: 'sarah@fintechglobal.com',
    phone: '+1 212 555 4321',
    value: 65000,
    stage: 'proposal',
    assignedTo: 'Michael Miller',
    createdAt: '2026-07-30',
  },
];

export const PLATFORM_DOCUMENTS: DocumentItem[] = [
  {
    id: 'doc-1',
    name: 'SrijanDev_Enterprise_Architecture_2026.pdf',
    category: 'project',
    size: '4.2 MB',
    updatedAt: '2026-08-01',
    author: 'Rajesh Bhatti',
    downloadUrl: '#',
  },
  {
    id: 'doc-2',
    name: 'Employee_Workforce_Policy_v4.pdf',
    category: 'policy',
    size: '1.8 MB',
    updatedAt: '2026-06-15',
    author: 'Michael Miller',
    downloadUrl: '#',
  },
  {
    id: 'doc-3',
    name: 'Q3_Financial_Forecast_Report.xlsx',
    category: 'financial',
    size: '2.5 MB',
    updatedAt: '2026-07-31',
    author: 'Priya Nair',
    downloadUrl: '#',
  },
];

export const PLATFORM_LOGS: ActivityLog[] = [
  {
    id: 'log-1',
    user: 'Rajesh Bhatti',
    action: 'Switched Active Portal context to Business Platform',
    target: 'System Header Switcher',
    timestamp: '10 mins ago',
    type: 'info',
  },
  {
    id: 'log-2',
    user: 'Aisha Sharma',
    action: 'Updated task "Fine-tune AI Agent RAG Extractor"',
    target: 'Task Manager #102',
    timestamp: '25 mins ago',
    type: 'success',
  },
  {
    id: 'log-3',
    user: 'Priya Nair',
    action: 'Clocked in at Headquarters Bengaluru',
    target: 'Attendance Log',
    timestamp: '1 hour ago',
    type: 'info',
  },
];
